apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: <sanskrutipawar>/calculator-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # (not necessary for console apps, but written for general practice)
